export default {
  LOGIN: "LOGIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  CREATE_BOARD_REQUEST: 'CREATE_BOARD_REQUEST',
  CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
  CREATE_BOARD_ERROR: 'CREATE_BOARD_ERROR',

  GET_BOARDS_REQUEST: 'GET_BOARDS_REQUEST',
  GET_BOARDS_SUCCESS: 'GET_BOARDS_SUCCESS',
  GET_BOARDS_ERROR: 'GET_BOARDS_ERROR',
};