export default {
  LOGIN: "LOGIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  CREATE_BOARD_REQUEST: 'CREATE_BOARD_REQUEST',
  CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
  CREATE_BOARD_ERROR: 'CREATE_BOARD_ERROR',

  GET_BOARDS_REQUEST: 'GET_BOARDS_REQUEST',
  GET_BOARDS_SUCCESS: 'GET_BOARDS_SUCCESS',
  GET_BOARDS_ERROR: 'GET_BOARDS_ERROR',

  GET_BOARD_BY_ID_REQUEST: 'GET_BOARD_BY_ID_REQUEST',
  GET_BOARD_BY_ID_SUCCESS: 'GET_BOARD_BY_ID_SUCCESS',
  GET_BOARD_BY_ID_ERROR: 'GET_BOARD_BY_ID_ERROR',

  REMOVE_BOARD_BY_ID_REQUEST: 'REMOVE_BOARD_BY_ID_REQUEST',
  REMOVE_BOARD_BY_ID_SUCCESS: 'REMOVE_BOARD_BY_ID_SUCCESS',
  REMOVE_BOARD_BY_ID_ERROR: 'REMOVE_BOARD_BY_ID_ERROR',

  CREATE_COLUMN_REQUEST: 'CREATE_COLUMN_REQUEST',
  CREATE_COLUMN_SUCCESS: 'CREATE_COLUMN_SUCCESS',
  CREATE_COLUMN_ERROR: 'CREATE_COLUMN_ERROR',

  GET_COLUMNS_REQUEST: 'GET_COLUMNS_REQUEST',
  GET_COLUMNS_SUCCESS: 'GET_COLUMNS_SUCCESS',
  GET_COLUMNS_ERROR: 'GET_COLUMNS_ERROR',

  REMOVE_COLUMN_REQUEST: 'REMOVE_COLUMN_REQUEST',
  REMOVE_COLUMN_SUCCESS: 'REMOVE_COLUMN_SUCCESS',
  REMOVE_COLUMN_ERROR: 'REMOVE_COLUMN_ERROR',

  CREATE_CARD_REQUEST: 'CREATE_CARD_REQUEST',
  CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',
  CREATE_CARD_ERROR: 'CREATE_CARD_ERROR',

  GET_CARDS_REQUEST: 'GET_CARDS_REQUEST',
  GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
  GET_CARDS_ERROR: 'GET_CARDS_ERROR',

  REMOVE_CARD_REQUEST: 'REMOVE_CARD_REQUEST',
  REMOVE_CARD_SUCCESS: 'REMOVE_CARD_SUCCESS',
  REMOVE_CARD_ERROR: 'REMOVE_CARD_ERROR',
};