export const userSelector = state => state.auth.user;
export const boardsSelector = state => state.boards;
export const newBoardSelector = state => state.newBoard;
export const currentBoardSelector = (state) => state.currentBoard;
export const currentBoardIndex = state => state.boards.currentBoardIndex;
export const columnsSelector = state => state.columns.columns;
export const cardsSelector = state => state.cards.cards;
export const boardActivities = state => state.activities.boardActivities;
export const cardActivities = state => state.activities.cardActivities;
