export const boardsSelector = state => state.boards;
export const userSelector = state => state.auth.user;
export const commentsSelector = state => state.comment.comments;
export const newBoardSelector = state => state.newBoard;
export const cardsSelector = state => state.cards.cards;
export const columnsSelector = state => state.columns.columns;
export const currentBoardSelector = state => state.currentBoard;
export const cardActivities = state => state.activities.cardActivities;
export const boardActivities = state => state.activities.boardActivities;
